### ISSUE TITLE
implement dashboard / homepage

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#312]
This should have a few steps, which I'll break out into separate issues: 

 - [x] disable excerpts on activity items (#311)
 - [x] make a profile widget with the logged-in user's avatar, profile completeness, and links to other personalized pages (#314) 
 - [x] make filter tabs that filter the activity stream with AJAX (#313)
 - [ ] make a new sidebar called "tabbed" that displays all its widgets as tabs (#315)
 - [x] add news rss, sites, resources as widgets to tabbed sidebar
 - [x] write script to add the widgets to new sidebars, to automate the rollout process.

**Comment by terrainsvagues** [comment]
The homepage should display (regardless of logged in/logged out status): 3 most recent blog posts, 3 most recent CORE deposits, 3 most recent forum posts
