### ISSUE TITLE
implement activity filter tabs for dashboard homepage

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#313]
see #312.

This could be broken up into these tasks: 

 - [x] construct a query string and AJAX filter for the "newsfeed" tab #318 
 - [x] start recording activity items for new members mlaa/cbox-auth#27
 - [x]  mix in official MLA site post activity items to newsfeed #320 
 - [x] trigger filters with `?type=` URL queries, and change the URL when a filter is clicked, as in #298 (#319)

**Comment by JonathanReeve** [comment]
It doesn't seem like there are any activity items of type `new_member` like the activity filter dropdown seems to suggest. We might have to start recording these.

**Comment by chriszarate** [comment]
Is our auth plugin short-circuiting them?

**Comment by JonathanReeve** [comment]
Maybe. I'll add that as a cbox-auth issue.
